### ISSUE TITLE
Please remove doubles 'Easter Egg'

### ISSUE THREAD

**Issue by goshdarngames** [kyzentun/consensual#29]
First off thanks for making this great Stepmania theme.  I mainly use it so that I can play random songs by difficulty from a large folder of songs and this theme does a great job of that.

Today I tried to play and was completely unable to because of your Easter Egg that sets the play mode to doubles.  I play with a dance pad and plugging in a second pad is not an option.  I have no idea how to change between singles and doubles so it was pretty frustrating.  

First I spent a long time trying to figure out why it was set to doubles and I could see no option to play singles.  Nor could I find any option in the menus relating to Easter Eggs when I found out that was the problem.  I had an hour free to play Stepmania and this was all wasted scrolling through menus and googling.  (weird stuff comes up when you google 'consensual' btw)

I'm all for special easter eggs and stuff but try to think of something that won't get in the way of playing so much.

**Comment by kyzentun** [comment]
Sorry about your chance to play today, but I thought the message on the first menu screen would be sufficient to tell people to turn off Easter Eggs.  (http://i.imgur.com/NNnJ42B.jpg)

https://github.com/kyzentun/consensual/commit/2f9de8617d629bc17608c4b1818cd34eddf75bab

**Comment by goshdarngames** [comment]
Well my experience was that I skipped through the title screen without even noticing the text there and when I loaded my songpacks a lot of songs were missing (as they didn't have a doubles setting).  My first thought was that my songs had somehow corrupted or something so I scrolled about and thought with dread that my SSD was dying (again).  It took me a long time to realise that the reason they weren't showing was that it was set to doubles - the little D wasn't enough for me to get it at first.

I then thought that I must have accidentally set it to double instead of single so I tried looking for the option to change between double and single.  I have never used double so I have no idea how to do this - the stepmania options menus are pretty confusing to me.  I have no idea what many of the settings do and I'm happy enough it works on default.  I saw the message about easter eggs but it didn't immediately dawn on me that it was what had set it to double.

After scrolling through all the menus a few times I decided to google how to switch between double and singles in consensual (this is where I found that googling 'consensual singles doubles' brings up weird results).  Here I found the github page and learned from a random forum post that the easter egg was setting everything to double.

I went back to stepmania and looked through the menus again for "Easter Egg" but I couldn't find any option that was related to it.  My time was running out so I just deleted the theme and went back to vanilla but having used theme for a few months it sucked that everything was plain old again and I only did one song before packing everything away.

Sorry to be so long-winded and over-dramatic but I just want you to get an idea what my user-experience with the Easter Egg was like.  I've used the theme pretty happily for months and I'm grateful for your time making it but I don't think restricting what game modes the user can use is a great thing to do for an Easter Egg.  

It made it so I couldn't play and I thought my game was broke and I don't even know what's so special about today anyway.  I think it'd be better to have a cool visual effect or a funny note skin that is purely cosmetic and doesn't go changing settings with no warning.  Even just a message explaining why it's a special day and some celebratory music on the menu.

**Comment by kyzentun** [comment]
Deleting the theme practically never solves problems.  Same goes for deleting stepmania.  The configuration isn't cleared when stepmania or the theme is deleted, so if the problem is there, it persists.

Consensual actually uses AutoSetStyle, which means that normally a single player can change between single and double charts on the music select screen, without going back to a style select screen.  (there used to be a menu for configuring which styles were visible and selectable by a player, but that got dropped when I had to rewrite every menu for the StepMania 5.1.-2 update.  The resulting config file is still loaded and used though)

Most of the options, I pick the best name I can think of, and hope for people to experiment with changing them to see what they do.  Maybe using the footer section at the bottom of the screen for option explanations would work? (since I mostly intend for people to set options on the select music screen)

If I ever work on this theme again, I'll try to make the stepstype of the currently selected chart more visible.  Prepending D to the difficulty isn't enough for anyone that isn't looking for it.

I guess I hit the wrong balance between making the "special day" message visible and avoiding disrupting the menu.  I could add some instructions for finding the easter egg option in the normal stepmania options. (it's in the advanced options) (consensual does not have its own easter eggs flag)  More knowledgable users would need be told that this will not disable toasty effects (which have their own flag in the player's profile).

Today happens to be my birthday, and double is substantially more fun than single (if you have two good pads to play it on).  That was the inspiration for this.  A cake icon would probably have been a better choice.

It's removed in the commit I linked, since I don't want to invest the time to do something different right now.  The April Fools stuff is still in though.  That turns on confetti, which should make people notice that something is up and see the message.

http://smbc-comics.com/index.php?id=3970

**Comment by goshdarngames** [comment]
Hey thanks for your reply.  Sorry if I was grouchy - I just wanted to try and explain my thought process and why it caused so much confusion.  Stepmania has so many menus and it's overwhelming trying to navigate them so when something doesn't work.  

Once again thanks for your work on the theme and I hope you had a nice birthday!

**Comment by kyzentun** [comment]
I honestly have no idea how to make the menus in Stepmania easier for new players to understand.  It's one of the most serious problems in Stepmania, and I don't even know how to approach it.  If you can come up with a good plan and explain it well, send it in.
